baseURL = 'https://main.d1e8gu8xpfj5t9.amplifyapp.com/'
languageCode = 'fr-FR'
title = 'Détourner'
theme = 'hugo-creative-portfolio-theme'

[params.meta]
  favicon = true


[params]
  about = 'about.md'
  logo = 'logo_detourner.png'
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Détourner est un atelier de création d'objets technologique atypique et divertissant."
  copyright = "&copy;2024 Détourner"
  sidebarAbout = ["Atelier de création d'objets"]
  email = "contact@detourner.fr"
  summary = "/introduction/introduction"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Objets"
  url = "objects/"
  home = true

  [[params.navlinks]]
  name = "A propos de"
  url = "about/"




