baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Détourner'
theme = 'researcher'

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

[params]
sitename = "Détourner"
copyrights = "detourner.fr"
defaultList = "global"
paginationLen = 3
projectsURL = "https://www.detourner.fr"
highlightjs = true
highlightjslanguages = ["r", "python", "stan"]
uselatex = true
progressively = false

[params.style]  # appearance options (can be omitted)
    fontFamily = "Calibri"
    fontSize = "13pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[menu]
	[[menu.main]]
	name = "A propos"
	url = "/pages/about"
	weight = 2




